Vagrant.configure("2") do |config|
  config.vm.box = "generic/ubuntu2204"
  
  config.vm.provider :libvirt do |lv|
    lv.cpus = 1
    lv.memory = 1024
  end
    
  config.vm.synced_folder ".", "/vagrant", 
    type: "nfs", 
    nfs_version: 4, 
    nfs_udp: false
  
  config.ssh.insert_key = false
  
  config.vm.define "ihhadjalS" do |server|
    server.vm.hostname = "ihhadjalS"
    server.vm.network "private_network", 
      ip: "192.168.56.110",
      libvirt__dhcp_enabled: false
    server.vm.provision "shell", path: "k3s-server.sh", privileged: true
  end
end