Vagrant.configure("2") do |config|
  config.vm.box = "generic/ubuntu2204"
  
  config.vm.synced_folder "./shared", "/vagrant_shared",
    type: "nfs",
    nfs_version: 4,
    nfs_udp: false
  
  config.vm.provider :libvirt do |lv|
    lv.cpus = 1
    lv.memory = 1024
    lv.driver = "kvm"
  end
  
  config.ssh.insert_key = false
  config.ssh.forward_agent = true
  
  config.vm.define "ihhadjalS", primary: true do |server|
    server.vm.hostname = "ihhadjalS"
    server.vm.network "private_network", 
      ip: "192.168.56.110",
      libvirt__network_name: "k3s-network",
      libvirt__dhcp_enabled: false,
      libvirt__forward_mode: "route"
    
    server.vm.provision "shell", path: "k3s-server-nfs.sh", privileged: true
  end
  
  config.vm.define "ihhadjalSW" do |agent|
    agent.vm.hostname = "ihhadjalSW"
    agent.vm.network "private_network", 
      ip: "192.168.56.111",
      libvirt__network_name: "k3s-network",
      libvirt__dhcp_enabled: false,
      libvirt__forward_mode: "route"
    
    agent.vm.provision "shell", path: "k3s-agent-nfs.sh", privileged: true
  end
end